# Generated by Django 4.2.20 on 2025-03-30 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=12, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('industry', models.CharField(max_length=100)),
                ('dividend', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('exdivdate', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(choices=[('C', 'CAD'), ('U', 'US$')], max_length=1)),
                ('frequency', models.CharField(choices=[('M', 'Monthly'), ('Q', 'Quarterly'), ('S', 'Semi Annual'), ('A', 'Annual'), ('N', 'No Div')], max_length=1)),
            ],
            options={
                'ordering': ['symbol'],
            },
        ),
    ]
