# Generated by Django 4.2.20 on 2025-03-30 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mystocks', '0002_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='dividend',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='exdivdate',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='frequency',
        ),
    ]
