# Generated by Django 4.2.20 on 2025-03-31 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystocks', '0003_remove_stock_currency_remove_stock_dividend_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='id',
        ),
        migrations.AlterField(
            model_name='stock',
            name='symbol',
            field=models.CharField(max_length=12, primary_key=True, serialize=False, unique=True),
        ),
    ]
