# Generated by Django 4.2.20 on 2025-03-31 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystocks', '0004_remove_stock_id_alter_stock_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='currency',
            field=models.CharField(choices=[('C', 'CAD'), ('U', 'US$')], default='C', max_length=1),
        ),
        migrations.AddField(
            model_name='stock',
            name='dividend',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='stock',
            name='exdivdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='frequency',
            field=models.CharField(choices=[('M', 'Monthly'), ('Q', 'Quarterly'), ('S', 'Semi Annual'), ('A', 'Annual'), ('N', 'No Div')], default='Q', max_length=1),
        ),
    ]
