# Generated by Django 4.2.20 on 2025-03-31 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystocks', '0005_stock_currency_stock_dividend_stock_exdivdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='fair_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='stock',
            name='ibes_mean',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='stock',
            name='lseg_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='ms_analyst',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='stock',
            name='ms_quant',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='stock',
            name='no_of_analysts',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
