# Generated by Django 4.2.20 on 2025-03-31 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystocks', '0006_stock_fair_value_stock_ibes_mean_stock_lseg_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='notes',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
