# Generated by Django 4.2.26 on 2025-12-01 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('symbol', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('industry', models.CharField(max_length=100)),
                ('notes', models.CharField(blank=True, max_length=1024)),
            ],
            options={
                'ordering': ['symbol'],
            },
        ),
    ]
