# Generated by Django 4.2.26 on 2025-12-01 23:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='img1',
            field=models.ImageField(blank='True', default='stocks/Default1.png', null='True', upload_to='stocks/'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='stock',
            name='img2',
            field=models.ImageField(blank='True', default='stocks/Default2.png', null='True', upload_to='stocks/'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='stock',
            name='last_update_1',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='last_update_2',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
