# Generated by Django 4.2.26 on 2026-01-04 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_stock_img1_stock_img2_stock_last_update_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='img1_last_analyst_entry',
            field=models.DateField(default='2025-01-01'),
        ),
        migrations.AddField(
            model_name='stock',
            name='img1_refreshed_on',
            field=models.DateField(default='2025-01-01'),
        ),
        migrations.AddField(
            model_name='stock',
            name='img2_refreshed_on',
            field=models.DateField(default='2025-01-01'),
        ),
    ]
