# Generated by Django 4.2.26 on 2026-01-04 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_stock_img1_last_analyst_entry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='img2_last_analyst_entry',
            field=models.DateField(default='2025-01-01'),
        ),
    ]
