# Generated by Django 4.2.26 on 2026-01-05 14:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_stock_img2_last_analyst_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='currency',
            field=models.CharField(choices=[('C', 'CAD'), ('U', 'USD')], default='C', max_length=1),
        ),
        migrations.AddField(
            model_name='stock',
            name='dividend',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='stock',
            name='ex_div_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='stock',
            name='frequency',
            field=models.CharField(choices=[('M', 'Monthly'), ('Q', 'Quarterly'), ('S', 'Semi-Annual'), ('A', 'Annually')], default='Q', max_length=1),
        ),
    ]
