# Generated by Django 4.2.26 on 2026-01-05 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_stock_currency_stock_dividend_stock_ex_div_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='dividend',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=6),
        ),
    ]
