# Generated by Django 4.2.26 on 2026-01-06 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0007_alter_stock_dividend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='img1_last_analyst_entry',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='img2_last_analyst_entry',
        ),
        migrations.AddField(
            model_name='stock',
            name='last_analyst_rating_entry',
            field=models.DateField(default='2025-07-01'),
        ),
        migrations.AddField(
            model_name='stock',
            name='last_baystreet_entry',
            field=models.DateField(default='2025-07-01'),
        ),
    ]
