# Generated by Django 4.2.26 on 2026-01-06 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0008_remove_stock_img1_last_analyst_entry_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='last_analyst_rating_entry',
            new_name='last_analyst_rating',
        ),
    ]
