# Generated by Django 4.2.26 on 2026-01-28 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0009_rename_last_analyst_rating_entry_stock_last_analyst_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='avg_cost',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='stock',
            name='price',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='stock',
            name='qty_owned',
            field=models.IntegerField(default=0, max_length=4),
        ),
    ]
