# Generated by Django 4.2.26 on 2026-02-08 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0010_stock_avg_cost_stock_price_stock_qty_owned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='qty_owned',
            field=models.IntegerField(default=0),
        ),
    ]
