# Generated by Django 4.2.26 on 2026-02-08 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0011_alter_stock_qty_owned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='last_analyst_rating',
            new_name='last_analyst_entry',
        ),
        migrations.AlterField(
            model_name='stock',
            name='avg_cost',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='stock',
            name='price',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=7),
        ),
    ]
