# Generated by Django 4.2.26 on 2026-02-12 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0012_rename_last_analyst_rating_stock_last_analyst_entry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='action',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='stock',
            name='analyst',
            field=models.CharField(choices=[('1', '1*'), ('2', '2*'), ('3', '3*'), ('4', '4*'), ('5', '5*')], default=0, max_length=2),
        ),
        migrations.AddField(
            model_name='stock',
            name='lseg',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='quant',
            field=models.CharField(choices=[('1', '1*'), ('2', '2*'), ('3', '3*'), ('4', '4*'), ('5', '5*')], default=0, max_length=2),
        ),
        migrations.AddField(
            model_name='stock',
            name='rating',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
