# Generated by Django 4.2.26 on 2026-02-12 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0013_stock_action_stock_analyst_stock_lseg_stock_quant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='analyst',
            field=models.CharField(choices=[('0', 'NR'), ('1', '1*'), ('2', '2*'), ('3', '3*'), ('4', '4*'), ('5', '5*')], default=0, max_length=2),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quant',
            field=models.CharField(choices=[('0', 'NR'), ('1', '1*'), ('2', '2*'), ('3', '3*'), ('4', '4*'), ('5', '5*')], default=0, max_length=2),
        ),
    ]
