# Generated by Django 4.2.26 on 2026-02-12 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0014_alter_stock_analyst_alter_stock_quant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='qty_owned',
            new_name='qty',
        ),
    ]
