# Generated by Django 4.2.26 on 2026-02-17 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0015_rename_qty_owned_stock_qty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='rating',
            new_name='ibes_mean',
        ),
        migrations.AddField(
            model_name='stock',
            name='analyst_count',
            field=models.CharField(default=0, max_length=2),
        ),
        migrations.AddField(
            model_name='stock',
            name='fair_value',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=7),
        ),
    ]
