# Generated by Django 4.2.26 on 2026-02-18 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0016_rename_rating_stock_ibes_mean_stock_analyst_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='analyst_count',
            new_name='count',
        ),
    ]
