# Generated by Django 4.2.26 on 2026-03-06 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0017_rename_analyst_count_stock_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('portfolio_name', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('held_at', models.CharField(blank=True, max_length=50, null=True)),
                ('currency', models.CharField(choices=[('C', 'CAD'), ('U', 'USD')], default='C', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Holdings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_owned', models.IntegerField(default=0)),
                ('avg_cost', models.DecimalField(decimal_places=3, default=0.0, max_digits=7)),
                ('notes', models.CharField(blank=True, max_length=100, null=True)),
                ('portfolio_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.portfolio')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='stocks.stock')),
            ],
        ),
    ]
