# Generated by Django 4.2.26 on 2026-04-29 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0018_portfolio_holdings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Holdings',
            new_name='Holding',
        ),
    ]
