# Generated by Django 4.2.26 on 2026-04-29 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0019_rename_holdings_holding'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='holding',
            options={'ordering': ['portfolio_name', 'symbol']},
        ),
        migrations.AlterField(
            model_name='holding',
            name='symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holding', to='stocks.stock'),
        ),
    ]
