# Generated by Django 4.2.26 on 2026-06-18 16:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0020_alter_holding_options_alter_holding_symbol"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="high52w",
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name="stock",
            name="low52w",
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name="stock",
            name="prev_close",
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name="stock",
            name="target_hign",
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name="stock",
            name="target_low",
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=7),
        ),
    ]
