# Generated by Django 4.2.26 on 2026-06-20 00:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0021_stock_high52w_stock_low52w_stock_prev_close_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="exchange",
            field=models.CharField(default=".TO", max_length=5),
        ),
    ]
