# Generated by Django 4.2.26 on 2026-06-20 00:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0022_stock_exchange"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="exchange",
            field=models.CharField(blank=True, default=".TO", max_length=5, null=True),
        ),
    ]
