# Generated by Django 4.2.26 on 2026-06-20 00:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0023_alter_stock_exchange"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stock",
            old_name="target_hign",
            new_name="target_high",
        ),
    ]
