# Generated by Django 4.2.26 on 2026-07-28 00:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0024_rename_target_hign_stock_target_high"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="target_range",
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name="stock",
            name="trading_range",
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4),
        ),
    ]
