# Generated by Django 4.2.26 on 2026-07-28 15:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0025_stock_target_range_stock_trading_range"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stock",
            old_name="target_range",
            new_name="target",
        ),
        migrations.RenameField(
            model_name="stock",
            old_name="trading_range",
            new_name="trading",
        ),
    ]
