# Generated by Django 4.2.26 on 2026-07-29 01:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0026_rename_target_range_stock_target_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="data",
            field=models.CharField(default="Y", max_length=1),
        ),
    ]
