# Generated by Django 4.2.26 on 2026-08-08 00:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0027_stock_data"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stock",
            old_name="dividend",
            new_name="dividend_rate",
        ),
        migrations.AddField(
            model_name="stock",
            name="dividend_yield",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name="stock",
            name="fifty_day_avg_change",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name="stock",
            name="two_hundred_day_avg_change",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
