# Generated by Django 4.2.26 on 2026-08-11 00:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0028_rename_dividend_stock_dividend_rate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="dividend_rate",
            field=models.DecimalField(
                decimal_places=4, default=0.0, max_digits=6, verbose_name="Div Amount"
            ),
        ),
    ]
