# Generated by Django 4.2.26 on 2026-08-12 00:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0029_alter_stock_dividend_rate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stock",
            name="avg_cost",
        ),
        migrations.RemoveField(
            model_name="stock",
            name="price",
        ),
        migrations.RemoveField(
            model_name="stock",
            name="qty",
        ),
    ]
