# Generated by Django 4.2.26 on 2026-08-13 22:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0030_remove_stock_avg_cost_remove_stock_price_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stock",
            old_name="data",
            new_name="api_data",
        ),
    ]
